# Pre-commit workflow - runs on every commit
name: Pre-commit Checks

on:
  push:
    branches: [ "**" ]  # All branches
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24'

jobs:
  pre-commit:
    name: Pre-commit Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-v2-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-v2-
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    # Fast syntax and format checks
    - name: Go format check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "❌ Code is not formatted. Run 'gofmt -s -w .'"
          gofmt -s -l .
          exit 1
        fi
        echo "✅ Code is properly formatted"

    - name: Go vet
      run: |
        go vet ./...
        echo "✅ Go vet passed"

    - name: Go mod tidy check
      run: |
        go mod tidy
        if ! git diff --quiet go.mod go.sum; then
          echo "❌ go.mod or go.sum not up to date. Run 'go mod tidy'"
          git diff go.mod go.sum
          exit 1
        fi
        echo "✅ go.mod and go.sum are up to date"

    # Fast compilation check (skip if not implemented)
    - name: Build check
      run: |
        echo "Testing compilation of implemented services..."
        if [ -f "cmd/api/main.go" ]; then
          go build -v ./cmd/api
          echo "✅ API service compiles successfully"
        else
          echo "⏸️  API main.go not implemented yet - skipping"
        fi
        if [ -f "cmd/scraper/main.go" ]; then
          go build -v ./cmd/scraper
          echo "✅ Scraper service compiles successfully"
        else
          echo "⏸️  Scraper main.go not implemented yet - skipping"
        fi
        if [ -f "cmd/mcp/main.go" ]; then
          go build -v ./cmd/mcp
          echo "✅ MCP service compiles successfully"
        else
          echo "⏸️  MCP main.go not implemented yet - skipping"
        fi
        echo "✅ Build check completed (implemented services only)"

    # Run only critical unit tests (fast feedback)
    - name: Critical unit tests
      run: |
        echo "Running critical unit tests on implemented packages..."
        
        # Test internal packages
        if ls internal/*/*.go >/dev/null 2>&1; then
          go test -short -tags=critical ./internal/...
          echo "✅ Internal package tests passed"
        else
          echo "⏸️  No Go files in internal/ - skipping tests"
        fi
        
        # Test pkg packages (if they have Go files)
        if find pkg/ -name "*.go" | grep -q .; then
          go test -short -tags=critical ./pkg/...
          echo "✅ Pkg package tests passed"
        else
          echo "⏸️  No Go files in pkg/ - skipping tests"
        fi
        
        echo "✅ Critical unit tests completed (implemented packages only)"

    # Secret detection  
    - name: Secret detection
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified --no-update

    # License check
    - name: License header check
      run: |
        # Check for license headers in Go files
        if find . -name "*.go" -not -path "./vendor/*" -exec grep -L "Copyright\|License" {} \; | head -5 | grep -q .; then
          echo "⚠️  Some Go files missing license headers"
          # Don't fail for now, just warn
        else
          echo "✅ License headers present"
        fi

    # Dependency vulnerability check (fast)
    - name: Go vulnerability check
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
        echo "✅ No known vulnerabilities"

  # Lint check (separate job for better parallelization)
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=3m --fast

  # Frontend pre-commit checks (optional - only runs if package.json exists)
  frontend-checks:
    name: Frontend Pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check if frontend exists
      id: frontend-check
      run: |
        if [ -f "web/static/package.json" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "📦 Frontend package.json found - running checks"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "⏸️  Frontend not implemented yet - skipping frontend checks"
          echo "📁 Expected: web/static/package.json"
          echo "✅ Frontend checks passed (no frontend to validate)"
        fi
    
    - name: Set up Node.js
      if: steps.frontend-check.outputs.exists == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/static/package-lock.json
        
    - name: Install dependencies
      if: steps.frontend-check.outputs.exists == 'true'
      working-directory: web/static
      run: npm ci --prefer-offline
      
    - name: ESLint
      if: steps.frontend-check.outputs.exists == 'true'
      working-directory: web/static
      run: npm run lint
      
    - name: Prettier check
      if: steps.frontend-check.outputs.exists == 'true'
      working-directory: web/static
      run: npm run format:check
      
    - name: TypeScript check (if applicable)
      if: steps.frontend-check.outputs.exists == 'true'
      working-directory: web/static
      run: |
        if [ -f "tsconfig.json" ]; then
          npm run type-check
        else
          echo "ℹ️  No TypeScript configuration found"
        fi

  # Security pre-commit (fast security checks only)
  security:
    name: Security Pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: gosec (fast mode)
      run: |
        echo "Installing gosec security scanner..."
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        echo "Running gosec security scan..."
        gosec -fmt json -out gosec.json -quiet ./...
        echo "✅ gosec security scan completed"
      continue-on-error: true

    - name: Check gosec results
      run: |
        if [ -f gosec.json ]; then
          HIGH_ISSUES=$(jq '.Stats.NumFound // 0' gosec.json)
          if [ "$HIGH_ISSUES" -gt 0 ]; then
            echo "⚠️  Found $HIGH_ISSUES security issues"
            jq -r '.Issues[]? | "⚠️  \(.file):\(.line) - \(.details)"' gosec.json | head -5
            echo "💡 Review security issues in Fast CI pipeline for details"
          else
            echo "✅ No security issues found by gosec"
          fi
        else
          echo "ℹ️  gosec results file not found - scan may have been skipped"
        fi

  # Status check
  pre-commit-complete:
    name: Pre-commit Complete
    runs-on: ubuntu-latest
    needs: [pre-commit, lint, frontend-checks, security]
    if: always()
    
    steps:
    - name: Check results
      run: |
        if [[ "${{ needs.pre-commit.result }}" == "success" && \
              "${{ needs.lint.result }}" == "success" && \
              "${{ needs.frontend-checks.result }}" == "success" && \
              "${{ needs.security.result }}" == "success" ]]; then
          echo "✅ All pre-commit checks passed!"
          echo "🚀 Ready for push to remote"
        else
          echo "❌ Some pre-commit checks failed:"
          echo "  • Pre-commit: ${{ needs.pre-commit.result }}"
          echo "  • Lint: ${{ needs.lint.result }}"
          echo "  • Frontend: ${{ needs.frontend-checks.result }}"
          echo "  • Security: ${{ needs.security.result }}"
          exit 1
        fi